- CMakeLists.txt
* Fix iconurl to use the `raw.githubusercontent.com` url
* Update contributors to match list introcuced in https://github.com/BrownBiomechanics/SlicerAutoscoperM/commit/bbab4dface5dabf8e5639b3d1af0954719cd3e34 through:
* https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/7
> DOC: Update homepage/contributors/iconurl metadata specified in CMakeLists.txt

- AutoscoperM/AutoscoperM.py
- CMakeLists.txt
- SuperBuild.cmake
- SuperBuild/External_Autoscoper.cmake
This pull-request updates the build-system based on the "SuperBuild" extension template and adds the "Autoscoper" external project referencing BrownBiomechanics/Autoscoper@e045314
* It configures Autoscoper setting output & install directories based of `Slicer_INSTALL_THIRDPARTY_*_DIR` variables.
* It configures Autoscoper with the following options:
- `Autoscoper_INSTALL_Qt_LIBRARIES` set to `OFF`
- `Autoscoper_INSTALL_SAMPLE_DATA` set to `OFF`
* In top-level CMakeLists.txt, it updates `EXTENSION_CPACK_INSTALL_CMAKE_PROJECTS` appending the Autoscoper project. This ensures Autoscoper and its dependencies are installed.
* Attempting to launch autoscoper from the build tree is not yet supported.
* Attempting to launch autoscoper on macOS is not supported. A pop indicating so is displayed. …
> Support standalone build as extension

- SuperBuild/External_Autoscoper.cmake
This fixes the following build error reported when building with GCC v7. This corresponds to the compiler associated with the [SlicerBuildEnvironment](https://github.com/Slicer/SlicerBuildEnvironment) `slicer/buildenv-qt5-centos7:latest` used to build & package Slicer application and associated extensions on Linux.
```
[ 50%] Building CXX object autoscoper/CMakeFiles/autoscoper.dir/src/net/Socket.cpp.o
/path/to/SlicerAutoscoperM-build/Autoscoper/autoscoper/src/net/Socket.cpp:49:10: fatal error: filesystem: No such file or directory
#include <filesystem>
^~~~~~~~~~~~
```
GCC v7 does not implement `<filesystem>` but it does have the Filesystem Technical Specification which is in `<experimental/filesystem>`.
References:
* https://en.cppreference.com/w/cpp/header/experimental/filesystem
* …
> COMP: Update Autoscoper to fix build using gcc7 & specify OpenGL_GL_PREFERENCE

- CMakeLists.txt
- SuperBuild.cmake
This commit excludes Autoscoper dependency if build on macOS.
> COMP: Build and package Autoscoper only on supported platform

- .github/workflows/commit-message.yml
- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- AutoscoperM/AutoscoperM.py
- pyproject.toml
Supersedes:
* https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/20
To ensure the GitHub actions workflow is triggered for the first time, this new pull-request was re-created from a branch directly pushed to the repository.
> Add GitHub actions workflows

- SuperBuild/External_Autoscoper.cmake
* Add `Autoscoper.exe`, `Glew lib`, and `Tiff lib` to `Autoscoper_LIBRARY_PATHS_LAUNCHER_BUILD`
* This fixes the issue with `shutil.which` not being able to find Autoscoper when built from source. 
* Closes #28
> Update launcher paths for Autoscoper

- SuperBuild/External_Autoscoper.cmake
This commit is a follow-up of 690c9d570 (COMP: Update build tree launcher settings to fix execution of Autoscoper) ensuring that Autoscoper can be started on system without OpenCL.dll already in the path.
> BUG: Fix Autoscoper launcher on system without system OpenCL library

- SuperBuild/External_Autoscoper.cmake
* Fix trailing comma when saving single volume tracking data so that the file can be loaded by other CVS reader (e.g numpy)
- Before: `X_data, Y_data, Z_data, YAW_data, PITCH_data, ROLL_data,`
- After: `X_data, Y_data, Z_data, YAW_data, PITCH_data, ROLL_data`
- See BrownBiomechanics/Autoscoper#130
* Documentation updates
* Update sources to explicitly reference `std` namespace.
* Add support for 3D kernels (`Kernel::block3d` and `Kernel::grid3d`)
- Not yet used
- It was originally integrated to support the computation of "Distance field" in  BrownBiomechanics/Autoscoper#87 which was closed in favor of BrownBiomechanics/Autoscoper#128
```
$ git shortlog 60b3d6ec0..b29d30f51 --no-merges
Anthony Lombardi (20):
ENH: Update OpenCL wrapper to support 3D kernels (PR-113)
DOC: Fix typos in …
```
> ENH: Update Autoscoper

- AutoscoperM/AutoscoperM.py
* Bug was initially fixed in the scripted module template in [PR #6720](https://github.com/Slicer/Slicer/pull/6720) from Slicer core.
* This module (AutoscoperM) was created in 2021 while the above PR was integrated in late 2022
* Closes #34 
* See also https://discourse.slicer.org/t/warning-of-observer-from-scripted-module-in-slicer-5-0-3/24735
> BUG: Fix observer warning

- AutoscoperM/AutoscoperM.py
Fix a regression introduced in 12b684ecb (ENH: Register sample data for AutoscoperM)
> BUG: Ensure downloaded sample data archives are reused if checksum match

- SuperBuild/External_Autoscoper.cmake
This is a follow-up of these commits:
* ff793c571 (COMP: Update Autoscoper to fix build using gcc7 & specify OpenGL_GL_PREFERENCE)
* 3a4eef8ae (COMP: Fix initial configuration on Linux)
to fix the following warning:
```
[  7%] Performing configure step for 'GLEW' loading initial cache file /work/Preview/S-0-E-b/SlicerAutoscoperM-build/Autoscoper-build/GLEW-prefix/tmp/GLEW-cache-Release.cmake CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindOpenGL.cmake:315 (message): Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when available.  Run "cmake --help-policy CMP0072" for policy details.  Use the cmake_policy command to set the policy and suppress this warning.
FindOpenGL found both a legacy GL library:
OPENGL_gl_LIBRARY: /usr/lib64/libGL.so
and GLVND libraries for …
```
> COMP: Update Autoscoper to ensure OpenGL_GL_PREFERENCE is passed to GLEW project

- AutoscoperM/AutoscoperMLib/IO.py
* Regression was caused by the improper removal of the default storage node of the temp volume created during IO._castVolume
* Regression was initially introduced in 52b5bdc
* See https://github.com/Slicer/Slicer/issues/6099
> BUG: Fix VTK memory leak in partial volume gen

- SuperBuild/External_Autoscoper.cmake
* Updates Autoscoper to the latest version (as of `2023-09-18`)
* Includes fix for incorrect viewport calculations (causes OpenCL buffer error)
* See https://github.com/BrownBiomechanics/Autoscoper/pull/204
* Includes fix for Linux build failures
* See https://github.com/BrownBiomechanics/Autoscoper/pull/198
> ENH: Update version of Autoscoper to include fixes for OpenCL and linux

- SuperBuild/External_Autoscoper.cmake
Fixes:
* https://github.com/BrownBiomechanics/Autoscoper/issues/207
* https://github.com/BrownBiomechanics/Autoscoper/pull/208
* https://github.com/BrownBiomechanics/Autoscoper/issues/203
* https://github.com/BrownBiomechanics/Autoscoper/pull/204
* https://github.com/BrownBiomechanics/Autoscoper/pull/212
* https://github.com/BrownBiomechanics/Autoscoper/issues/217
* https://github.com/BrownBiomechanics/Autoscoper/pull/219
Features:
* https://github.com/BrownBiomechanics/Autoscoper/issues/197
* https://github.com/BrownBiomechanics/Autoscoper/pull/147
* https://github.com/BrownBiomechanics/Autoscoper/pull/205
* https://github.com/BrownBiomechanics/Autoscoper/issues/206
* https://github.com/BrownBiomechanics/Autoscoper/pull/209
* https://github.com/BrownBiomechanics/Autoscoper/pull/222 …
> ENH: Update Autoscoper with various enhancements and fixes

- SuperBuild/External_Autoscoper.cmake
Refactor the Particle Swarm Optimization (PSO) implementation by introducing a specialized Particle data structure alongside a particle collection. This structure allows us to efficiently manage and track computed Normalized Cross-Correlation (NCC) values for each particle. As a result, we now evaluate each particle only once per iteration, as opposed to between 2 and 5 times in the worst-case scenario.
This optimization has led to a remarkable reduction in per-frame execution time on a typical workstation using the OpenCL back-end, dropping it from the range of 9 to 18 seconds to a much-improved 3 to 6 seconds.
List of changes:
```
$ git shortlog 73eb359dc..4bdedd802 --no-merges
Anthony Lombardi (1):
PERF: Introduce particle data structure for PSO
```
> PERF: Update Autoscoper to include PSO optimization

- SuperBuild/External_Autoscoper.cmake
List of changes:
```
$ git shortlog 4bdedd802..4704f9b79 --no-merges
Anthony Lombardi (2):
BUG: Fix PSO Particle struct position initialization (#232)
BUG: Clip bounds of DRR projection to the bounds of the radiograph
Jean-Christophe Fillion-Robin (1):
DOC: Document Camera::calculateImagePlane
```
> BUG: Update Autoscoper to include DRR projection fixes

- SuperBuild/External_Autoscoper.cmake
List of changes:
```
$ git shortlog 4704f9b79..e14b2da04 --no-merges
Jean-Christophe Fillion-Robin (3):
COMP: Remove unused AutoscoperMainWindow::rand_gen_main() function
STYLE: Fix typo renaming function "intializeRandom" to "initializeRandom"
BUG: Fix seeding of random number generator
```
> BUG: Update Autoscoper to fix seeding of random number generator

- SuperBuild/External_Autoscoper.cmake
Summary:
* Support Autoscoper start from windows build-tree fixing launcher settings
* Fix casing of GLEW and TIFF library paths in build-tree launcher settings
> Support running Autoscoper using `SlicerWithSlicerAutoscoperM` fixing build-tree launcher settings

- AutoscoperM/AutoscoperM.py
- AutoscoperM/Resources/UI/AutoscoperM.ui
- CMakeLists.txt
- SuperBuild.cmake
- SuperBuild/External_Autoscoper-CUDA.cmake
- SuperBuild/External_Autoscoper-OpenCL.cmake
- SuperBuild/External_Autoscoper.cmake
Build-system updates:
- Removed support for setting Autoscoper_RENDERING_BACKEND option.
- Introduced an explicit AutoscoperM-OpenCL external project.
- Associated Autoscoper "_DIR" variables with the label "Autoscoper_DIRS" allowing to update install and fix-up rules based on the different Autoscoper builds.
- Updated external project variables depending on the project name to use `${proj}_` prefix instead of the hard-coded `Autoscoper_` one.
AutoscoperM module updates:
- Updated AutoscoperM module to include a combobox for selecting the rendering backend. The combobox is dynamically populated based on the available Autoscoper executables found in the environment (e.g., autoscoper-CUDA or autoscoper-OpenCL).
Note: The distribution of the CUDA variant of Autoscoper ("autoscoper-CUDA") …
> Support integrating backend-specific Autoscoper executable & enable CUDA backend

- CMakeLists.txt
- SuperBuild.cmake
- SuperBuild/External_Autoscoper.cmake
This commit updates the Autoscoper project by replacing the deprecated[^1] `FindCUDA` CMake module with the more robust and first-class support for CUDA language. The changes leverage the following key features introduced in various CMake versions:
[^1]: https://cmake.org/cmake/help/latest/module/FindCUDA.html
- 3.8: Support by the Makefile Generators and the Ninja generator on Linux, macOS, and Windows See https://cmake.org/cmake/help/latest/release/3.8.html#cuda\
- 3.9: Support by the Visual Studio Generators for VS 2010 and above. See https://cmake.org/cmake/help/latest/release/3.9.html#languages
- 3.17: Introduction of FindCUDAToolkit See https://cmake.org/cmake/help/latest/release/3.17.html#modules and https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#module:FindCUDATool …
> ENH: Update Autoscoper modernizing CUDA integration

- SuperBuild/External_Autoscoper.cmake
In addition of UI fix related to volume selection, it also fixes the use of the "delete" key for removing a pose on a frame.
List of Autoscoper changes:
```
$ git shortlog 22b1a41e0..4d2eec33f --no-merges
Anthony Lombardi (3):
BUG: Fix Volume item selection area
ENH: Reenable original delete functionality
ENH: Update interpolation to use Quaternions rather than eulers (#255)
Jean-Christophe Fillion-Robin (7):
STYLE: Remove redundant header guard from "Socket.h"
STYLE: Improve C++ source files formatting using uncrustify
ENH: Add clang-format configuration & associated exceptions
STYLE: Consistent formatting of C++ sources using clang-format
ENH: Update pre-commit config to include "clang-format"
STYLE: Ignore source files formatting changes in blame history
STYLE: Cleanup clang-format …
```
> ENH: Update Autoscoper with Quaternion support

- SuperBuild.cmake
- SuperBuild/External_Autoscoper.cmake
Ensure `CUDACXX` env. var is properly set and also update Autoscoper to ensure the corresponding compiler is found within the Autoscoper inner build.
Follow-up of f732df9 ("ENH: Update Autoscoper modernizing CUDA integration", 2024-02-12)
List of Autoscoper changes:
```
$ git shortlog 4d2eec33f..cebc017fe --no-merges
Jean-Christophe Fillion-Robin (1):
COMP: Ensure Autoscoper inner-build is built with expected CUDA compiler on Linux
```
> COMP: Fix Linux build with Autoscoper CUDA backend enabled

- AutoscoperM/AutoscoperM.py
- AutoscoperM/AutoscoperMLib/RadiographGeneration.py
- TrackingEvaluation/TrackingEvaluationLib/data.py
The generated API documentation reports the types based on the type annotations.
> DOC: Remove redundant sphinx directives duplicating type annotations

- AutoscoperM/AutoscoperM.py
- AutoscoperM/AutoscoperMLib/IO.py
- AutoscoperM/AutoscoperMLib/RadiographGeneration.py
- AutoscoperM/AutoscoperMLib/SubVolumeExtraction.py
- AutoscoperM/Resources/UI/AutoscoperM.ui
- CalculateDataIntensityDensity/CalculateDataIntensityDensity.py
- CalculateDataIntensityDensity/CalculateDataIntensityDensity.xml
- SuperBuild/External_Autoscoper.cmake
- VirtualRadiographGeneration/VirtualRadiographGeneration.py
- VirtualRadiographGeneration/VirtualRadiographGeneration.xml
- pyproject.toml
* Enables support for multi-volumes to be passed through the pipelines
* Centers volumes on [0,0,0]
* Closes #61 
* Closes #59
* Closes #83
* Closes #84 
Related pull requests:
* https://github.com/BrownBiomechanics/Autoscoper/pull/277
ToDo
> 4DCT / Sequential 3DCT

- AutoscoperM/AutoscoperM.py
- AutoscoperM/Resources/UI/AutoscoperM.ui
First of two PRs to address #107 
This pull request update the "Pre-processing" tab by moving the "Partial Volume Generation" section the "VRG Generation" ones.
| Before | After |
|--|--|
| ![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/219043/eb53518b-f79c-4ef0-8c95-08b70bf21958) | ![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/219043/df6e2c92-dce2-47e3-8a89-5efe5d1f45a9) |
As well as adds a dialog box to ensure the user is aware that they have to run "VRG Generation - Automatic Camera Placement" before the "Partial Volume Generation" if that is the pipeline they wish to run
> ENH: Reorganize the pre-processing UI and add PV confirmation

- AutoscoperM/AutoscoperM.py
- AutoscoperM/Resources/UI/AutoscoperM.ui
* Adds DICOM2AUT tfm
* Splits `{bone}.tfm` into `{bone}_t.tfm` and `{bone}_scale.tfm`
* Renames and addresses issues with Slicer2Autoscoper transform (now PVOL2AUT)
> Transformation Update

- AutoscoperM/AutoscoperM.py
Previously, the PV visualized would be spatially based in DICOM space. Now they are loaded in and transformed from the TIFF stacks to better reflect the transform hierarchy.
Result of the PV Generation:
> ENH: Adjust PV visualization to better reflect transform hierarchy

- AutoscoperM/AutoscoperM.py
At the end of the partial volume generation process, our approach for matching the generated `*_t.tfm` and `*_scale.tfm` transforms to their corresponding `*.tif` partial volume incorrectly relied on the order of the files as found by `glob`.
The order of items returned by the function cannot be relied upon according to the [docs](https://docs.python.org/3/library/glob.html#glob.glob), so the index of each segment's corresponding volume and transforms in the lists `vols`, `tfms_t` and `tfms_scale` were not guaranteed to be the same. It sometimes resulted in the volume nodes being rendered with the wrong transforms applied to them when volume generation was finished.
Example: when trying to generate PVs from the the segments called `Segment_1` and `Segment_11` (running on Windows),
Each of …
> BUG: Fix wrong transformation layers applied to generated PVs

- AutoscoperM/AutoscoperM.py
Closes https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/133
To reduce clutter for the app users, after the generation of partial volumes in the pre-processing module, only the combined scale and translation transformation layer is loaded and applied onto each PV, instead of the two separate scale and translation trasnforms. I.e., `{}.tfm` is loaded and applied instead of `{}_t.ftm` and `{}_scale.tfm`.
All files are still written to the output directory as part of the PV generation proceess as before.
> ENH: Load combined scale and translation transforms to generated PVs

- AutoscoperM/AutoscoperM.py
- AutoscoperM/AutoscoperMLib/IO.py
- AutoscoperM/Resources/UI/AutoscoperM.ui
Resolves https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/131, resolves #145.
These changes are aimed to improve the user workflow in the Pre-Processing module, specifically targeting the improvement of the Autoscoper configuration file generation. Further changes to improve error handling to make it more user-friendly are to be continued in a separate upcoming PR.
Changes in this PR include:
* 'Volume Node' and 'Output Directory' at top of UI were swapped
* 'Trial Name' moved to the config generation section as the '<blank>'.cfg field
* The segmentation generation section was redesigned to better convey the two separate generation methods
* The 'Adavnced Options' sections was renamed to 'Default Subdirectories', moved below the 'Segmentation Generation' section, and is now …
> ENH: Update Pre-Processing UI to improve BVR workflow

- AutoscoperM/AutoscoperM.py
- AutoscoperM/AutoscoperMLib/ErrorUtils.py
- AutoscoperM/AutoscoperMLib/Validation.py
- AutoscoperM/CMakeLists.txt
As a follow up to https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/141, this PR improves the error reporting of the pre-processing module for better user friendliness. Namely, the error handling code was refactored to better report a meaningful error message to the UI user when an exception is raised (like what specific field(s) has the invalid value). The error is still reported to the error log for CLI users.
| Example Error Before | Example Error After |
|----|----|
|  ![Screenshot 2024-12-19 115034](https://github.com/user-attachments/assets/1a3408a8-4ea9-4404-b1a1-8022cc729c3c) | ![Screenshot 2024-12-19 120300](https://github.com/user-attachments/assets/cf593b2c-5a56-415f-87c2-1ea8785575c6) |
| ![Screenshot 2024-12-19 …
> ENH: Improve pre-processing error handling for UI user friendliness

- AutoscoperM/AutoscoperM.py
- TrackingEvaluation/TrackingEvaluation.py
Addresses https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/156, incorporates data as provided by @jdholt04 in https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/138.
The [sample data](https://github.com/BrownBiomechanics/Autoscoper/releases/tag/sample-data) was updated to rename the `Meshes` folder name to `Models`, include the nrrd source CT from which partial volumes were (and can be) created to the `Scene` folder, and add the corresponding transform files to the `Transforms` directory.
> ENH: Update the Knee sample data

- AutoscoperM/AutoscoperM.py
- AutoscoperM/AutoscoperMLib/IO.py
- AutoscoperM/Resources/UI/AutoscoperM.ui
Resolves https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/160.
The changes follow up on https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/140 to remove the unused function `extractSubVolumeForVRG` as well as all other code associated with the calculation and export of `.tra` files during the generation of partial volumes in the pre-processing module.
> BUG: Remove more VRG Generation relics

- AutoscoperM/AutoscoperM.py
- TrackingEvaluation/TrackingEvaluation.py
Addresses [#156](https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/156), incorporates data as provided by @amymmorton in https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/138#issuecomment-2651569270.
As a follow up to https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/159, the Wrist [sample data](https://github.com/BrownBiomechanics/Autoscoper/releases/tag/sample-data) was also updated to rename the `Meshes` folder name to `Models`, include the `.nrrd` source CT data to the `Scene` folder, and add the corresponding partial volume and transform files to the `Volumes` and `Transforms` directories.
> ENH: Update the Wrist sample data

- AutoscoperM/AutoscoperM.py
Addresses TODO in https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/138#issuecomment-2597009245.
This change improves the error checking for partial volume generation by warning the user before (potentially) overwriting existing results in the output directories. The provided output paths are checked before the PV generation routine is run so that if the subdirectories contain any existing files, the user is prompted whether or not to continue.
> ENH: Check for existing PV output files before generation

- AutoscoperM/AutoscoperM.py
- AutoscoperM/AutoscoperMLib/IO.py
- Hierarchical3DRegistration/Hierarchical3DRegistration.py
- Hierarchical3DRegistration/Hierarchical3DRegistrationLib/TreeNode.py
- Hierarchical3DRegistration/Resources/UI/Hierarchical3DRegistration.ui
Reimplements https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/99 following the approach discussed in:
- https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/149
- https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/150
- https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/151
and using some of the logic proposed in https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/152.
Tested using https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/110.
TODO:
**Edit: This will be outsourced to another team member**
**Edit: Not to be tackled immediately**
> ENH: Reimplement Hierarchical 3D Registration with ROI cropped volumes

- SuperBuild/External_Autoscoper.cmake
Fix the `fix_autoscoper_rpath` step so that it appropriately consider the variable `${proj}_ARTIFACT_SUFFIX` introduced in 566a540 ("ENH: Support integrating backend-specific Autoscoper executable", 2023-12-13)
> COMP: Ensure fix_autoscoper_rpath step completes on macOS

- AutoscoperM/AutoscoperM.py
- AutoscoperM/Resources/UI/AutoscoperM.ui
- SuperBuild.cmake
- SuperBuild/External_Autoscoper-CUDA-CollisionDetection.cmake
- SuperBuild/External_Autoscoper-OpenCL-CollisionDetection.cmake
- SuperBuild/External_Autoscoper.cmake
Resolves https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/174
This PR follows up on https://github.com/BrownBiomechanics/Autoscoper/pull/295 to distribute the compiled binaries of Autoscoper when compiled with or without the collision detection feature enabled. 
There should now be a matrix of binaries built and able to be loaded, either with a CUDA/OpenCL (or neither) backend, and with or without collision detection enabled. 
TODO: 
- Add VTK dependency
- Blocked until https://github.com/BrownBiomechanics/Autoscoper/pull/295 determines the final set of CMake options to build Autoscoper with collision detection enabled/disabled.
> ENH: Integrate Autoscoper compiled with collision detection

- SuperBuild.cmake
Follow-up of 1f5a694 ("ENH: Build and package Autoscoper built with Collision Detection enabled", 2025-04-16) ensuring location of CUDA toolkit is associated with `Autoscoper-CUDA-CollisionDetection` project.
> COMP: Fix build of Autoscoper CUDA with collision detection enabled
